# modules/utils/keywords_fr_en.py
import re


# 🛑 Stopwords pour le filtrage contextuel FR/EN
STOPWORDS = {
    "fr": {"le", "la", "les", "un", "une", "des", "du", "de", "en", "dans", "sur", "par", "avec", "pour", "au", "aux", "et", "à", "ce", "cette", "ces", "qui", "que"},
    "en": {"the", "a", "an", "of", "on", "in", "and", "to", "for", "with", "from", "by", "at", "as", "that", "which"}
}

FR_TO_EN_LEXICON = {
    "élastique":"elastic","élastiques":"elastic",
    "inélastique":"inelastic", "inélastiques":"inelastic",
    "capturées": "capture", "capturés": "capture", "capturee": "capture", "capturée": "capture",
    "capture": "capture", "captures": "capture", "capturés": "capture", "capturées": "capture",
    "fission": "fission", "scission": "fission", "fissionnée": "fission", "fissionnées": "fission",
    "désintégration": "decay", "retrodiffusion": "downscattering",
    "énergie": "energy", "energies": "energy", "énergies": "energy",
    "poids": "weight", "poids moyen": "weight", "masse": "weight",
    "temps": "time", "durée": "time", "retard": "time",
    "valeur": "value", "valeurs": "value", "score": "value", "résultat": "value",
    "surface": "surface", "surfaces": "surface", "paroi": "surface",
    "particule": "particle", "particules": "particles", "particule chargée": "charged-particle",
    "collision": "collision", "collisions": "collision", "interaction": "collision",
    "source": "source", "sources": "source", "banque": "bank", "banques": "bank",
    "terminaison": "termination", "terminaisons": "termination", "fin": "termination",
    "angle": "angle", "direction": "angle", "cos": "angle",
    "matériau": "material", "matériaux": "material", "couche": "material", "milieu": "material",
    "cellule": "cell", "cellules": "cells", "région": "cell",
    "importance": "importance", "pondération": "importance",
    "photons": "photon", "photon": "photon", "gamma": "photon",
    "protons": "proton", "proton": "proton",
    "électrons": "electrons", "électron": "electron",
    "alpha": "alpha", "alphas": "alpha",
    "triton": "triton", "tritons": "triton",
    "deuton": "deuteron", "deutons": "deuteron", "deuterium": "deuteron",
    "helium": "alpha", "he-3": "helium-3", "3he": "helium-3", "helion": "helium-3",
    "annihilation": "annihilation", "fluorescence": "fluorescence", "recul": "recoil",
    "photo-nucléaire": "photonuclear", "photo-nucléaire": "photo-nuclear","photo-nucléaires": "photo-nuclear", "photonucléaire": "photonuclear", "photons nucléaires": "photonuclear",
    "roulette": "roulette", "échantillonnage": "sampling",
    "réaction": "reaction", "réactions": "reaction", "interaction nucléaire": "reaction",
    "perte": "loss", "perdu": "lost", "perdus": "lost", "disparu": "lost", "disparus": "lost",
    "escaped": "escape", "échappement": "escape",
    "dxtran": "dxtran", "adjoint": "adjoint", "noeud": "node", "nœud": "node",
    "événement": "event", "événements": "event", "historique": "history",
    "tally": "tally", "tallies": "tally", "détecteur": "tally", "f": "tally", "fonction de comptage": "tally",
    "résultats": "value", "moyenne": "mean", "écart": "std", "somme": "sum", "maximum": "max", "minimum": "min",
    "léger":"light","légers":"light", "lourd":"heavy", "lourds":"heavy",
}

# For info only
PTRAC_ENUMS = {
    "PtracEventType": {
        "SRC": 1000,
        "BNK": 2000,
        "SUR": 3000,
        "COL": 4000,
        "TER": 5000,
        "LST": 9000
    },

    "PtracBankType": {
        "BNK_DXT_TRACK": 1,
        "BNK_ERG_TME_SPLIT": 2,
        "BNK_WWS_SPLIT": 3,
        "BNK_WWC_SPLIT": 4,
        "BNK_UNC_TRACK": 5,
        "BNK_IMP_SPLIT": 6,
        "BNK_N_XN_F": 7,
        "BNK_N_XG": 8,
        "BNK_FLUORESCENCE": 9,
        "BNK_ANNIHILATION": 10,
        "BNK_PHOTO_ELECTRON": 11,
        "BNK_COMPT_ELECTRON": 12,
        "BNK_PAIR_ELECTRON": 13,
        "BNK_AUGER_ELECTRON": 14,
        "BNK_PAIR_POSITRON": 15,
        "BNK_BREMSSTRAHLUNG": 16,
        "BNK_KNOCK_ON": 17,
        "BNK_K_X_RAY": 18,
        "BNK_N_XG_MG": 19,
        "BNK_N_XF_MG": 20,
        "BNK_N_XN_MG": 21,
        "BNK_G_XG_MG": 22,
        "BNK_ADJ_SPLIT": 23,
        "BNK_WWT_SPLIT": 24,
        "BNK_PHOTONUCLEAR": 25,
        "BNK_DECAY": 26,
        "BNK_NUCLEAR_INT": 27,
        "BNK_RECOIL": 28,
        "BNK_DXTRAN_ANNIHIL": 29,
        "BNK_N_CHARGED_PART": 30,
        "BNK_H_CHARGED_PART": 31,
        "BNK_N_TO_TABULAR": 32,
        "BNK_MODEL_UPDAT1": 33,
        "BNK_MODEL_UPDATE": 34,
        "BNK_DELAYED_NEUTRON": 35,
        "BNK_DELAYED_PHOTON": 36,
        "BNK_DELAYED_BETA": 37,
        "BNK_DELAYED_ALPHA": 38,
        "BNK_DELAYED_POSITRN": 39
    },

    "PtracTerminationType": {
        "TER_ESCAPE": 1,
        "TER_ENERGY_CUTOFF": 2,
        "TER_TIME_CUTOFF": 3,
        "TER_WEIGHT_WINDOW": 4,
        "TER_CELL_IMPORTANCE": 5,
        "TER_WEIGHT_CUTOFF": 6,
        "TER_ENERGY_IMPORTANCE": 7,
        "TER_DXTRAN": 8,
        "TER_FORCED_COLLISION": 9,
        "TER_EXPONENTIAL_TRANSFORM": 10,

        "TER_N_DOWNSCATTERING": 11,
        "TER_N_CAPTURE": 12,
        "TER_N_N_XN": 13,
        "TER_N_FISSION": 14,
        "TER_N_NUCLEAR_INTERACTION": 15,
        "TER_N_PARTICLE_DECAY": 16,
        "TER_N_TABULAR_BOUNDARY": 17,

        "TER_P_COMPTON_SCATTER": 11,
        "TER_P_CAPTURE": 12,
        "TER_P_PAIR_PRODUCTION": 13,
        "TER_P_PHOTONUCLEAR": 14,

        "TER_E_SCATTER": 11,
        "TER_E_BREMSSTRAHLUNG": 12,
        "TER_E_INTERACTION_DECAY": 13,

        "TER_GENNEUT_NUCLEAR_INTERACTION": 11,
        "TER_GENNEUT_ELASTIC_SCATTER": 12,
        "TER_GENNEUT_DECAY": 13,

        "TER_GENCHAR_MULTIPLE_SCATTER": 11,
        "TER_GENCHAR_BREMSSTRAHLUNG": 12,
        "TER_GENCHAR_NUCLEAR_INTERACTION": 13,
        "TER_GENCHAR_ELASTIC_SCATTER": 14,
        "TER_GENCHAR_DECAY": 15,
        "TER_GENCHAR_CAPTURE": 16,
        "TER_GENCHAR_TABULAR_SAMPLING": 17
    },

    "PtracDataType": {
        "NPS": 1,
        "FIRST_EVENT_TYPE": 2,
        "NPSCELL": 3,
        "NPSSURFACE": 4,
        "TALLY": 5,
        "VALUE": 6,
        "NEXT_EVENT_TYPE": 7,
        "NODE": 8,
        "NSR": 9,
        "ZAID": 10,
        "RXN": 11,
        "SURFACE": 12,
        "ANGLE": 13,
        "TERMINATION_TYPE": 14,
        "BRANCH": 15,
        "PARTICLE": 16,
        "CELL": 17,
        "MATERIAL": 18,
        "COLLISION_NUMBER": 19,
        "X": 20,
        "Y": 21,
        "Z": 22,
        "U": 23,
        "V": 24,
        "W": 25,
        "ENERGY": 26,
        "WEIGHT": 27,
        "TIME": 28,
        "SOURCE_TYPE": 29,
        "BANK_TYPE": 30
    }
}
